baseURL = "https://thetucks.com"
languageCode = "en-uk"
title = "A menagerie of technical peccadillos"
author = "Steve Tuck"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true
Paginate = 12
copyright = "Steve Tuck"

theme = "gohugo-theme-ananke-mod"
uglyurls = true

[indexes]
  tag = "tags"
  topic = "topics"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "Home"
    url = "/"

#
# Note https://github.com/theNewDynamic/gohugo-theme-ananke/issues/85
# Need to name directory content/post (not posts) for Ananke theme to display dates of posts
#

[params]
  facebook = "https://www.facebook.com/tuck1s/"
  twitter = "https://www.twitter.com/tuck1s/"
  linkedin = "https://www.linkedin.com/in/steventuck/"
  github = "https://www.github.com/tuck1s/"
  stackoverflow = "https://stackoverflow.com/users/8545455/steve"
  featured_image = "/beeb.png"
  favicon = "/favicon.ico"

  background_color_class = "bg-dark-gray"
  cover_dimming_class = "bg-black-40"
  env = "production" # needed for robots.txt enabled
