baseURL = "https://thetucks.com"
languageCode = "en"
title = "A menagerie of technical peccadillos"
author = "Steve Tuck"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true
Paginate = 12
copyright = "Steve Tuck"

theme = "ananke"
#uglyurls = true
#canonifyURLs = true

[indexes]
  tag = "tags"
  topic = "topics"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "Home"
    url = "/"

[params]
  facebook = "https://www.facebook.com/tuck1s/"
  twitter = "https://www.twitter.com/tuck1s/"
  linkedin = "https://www.linkedin.com/in/steventuck/"
  github = "https://www.github.com/tuck1s/"
  stackoverflow = "https://stackoverflow.com/users/8545455/steve"
  favicon = "/favicon.ico"

  background_color_class = "bg-dark-gray"
  cover_dimming_class = "bg-black-40"
  env = "production" # needed for robots.txt enabled
  site_logo = "/beeb.png"
